name: WASM Demo
on:
  push:
    branches: [main]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  checks: write

jobs:
  demo-ghpages:
    name: Update Demos in GitHub Pages
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: jetli/wasm-bindgen-action@v0.1.0
        with:
          version: 'latest'
      - uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-unknown
          toolchain: 1.71.0
          override: true
      - name: Build docs
        env:
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          mkdir demo
          for demowasm in $(cd target/wasm32-unknown-unknown/release; ls *.wasm | grep -v -); do
              wasm-bindgen target/wasm32-unknown-unknown/release/$demowasm --out-dir demo/ --target web
              cat > demo/${demowasm%.*}.html <<EOF
          <html lang="en-us">
              <head>
                  <script type="module">
                      import init from './${demowasm%.*}.js';
                      var res = await init();
                      res.start();
                  </script>
              </head>
              <body>
                  <script>
                      document.body.addEventListener("contextmenu", (e) => {
                          e.preventDefault();
                          e.stopPropagation();
                      });
                  </script>
              </body>
          </html>
          EOF
          done &&
          cp -R assets/ demo/
      - name: Add read permissions
        run: |-
          chmod --recursive +r demo
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: demo
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
